/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://hmhfqmu65fallhydqn3vngb7mi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-f37tsiocivhspmyomcqbriolje",
    "aws_cognito_identity_pool_id": "us-east-2:a2b11ab7-f726-4a9e-923a-f9a182b4b3e3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VHO9vA0yC",
    "aws_user_pools_web_client_id": "57bkim50bgs3sbjj7mc3crugpv",
    "oauth": {},
    "aws_user_files_s3_bucket": "notty415db1a22ad846a5bc17bd7dfc4003b395310-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
